// form-votacao-online/src/app/cabine/cabine.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';

type OptionsType = {
    option: string,
    count: number
}

@Component({
    selector: 'cabine',
    templateUrl: './cabine.component.html',
    styleUrls: ['./cabine.component.scss']
})
export class CabineComponent {
    @Input() options!: OptionsType[];
    @Output() click = new EventEmitter<number>();

}

<div class="options">
    <button *ngFor="let option of options; index as i" (click)="click.emit(i)">
        {{option.option}}
    </button>
</div>

// form-votacao-online/src/components/Cabine/index.tsx
import React from 'react'

import './style.scss'

type VoteOptionsType = {
    option: string;
    count: number;
}

type Props = {
    voteOptions: VoteOptionsType[];
    onVote: (index: number) => void;
}

const Cabine = ({ voteOptions, onVote }: Props) => {

    const botoes = voteOptions.map((option, index) => (
        <button key={index}
            onClick={() => onVote(index)}>
            {option.option}
        </button>
    ))
    return (
        <div className="options">
            {botoes}
        </div>
    )
}

export default Cabine;
