// form-votacao-online/src/components/VoteForm.vue
<template>
    <div>
        <h2>Formulário de votação</h2>
        <form @submit.prevent="onSubmit" class="form-horizontal">
            <Input
                type="textarea"
                label="Enunciado"
                v-model="vt.statement"
                placeholder="Digite o enunciado da votação"
                isRequired="true"
                :error="errors['statement']"
                @input="touched['statement'] = true"
                @blur="checkField('statement')"
            />
            <br />
            <Input
                label="Opção 1"
                v-model="vt.option1"
                placeholder="Digite a 1ª opção"
                isRequired="true"
                :error="errors['option1']"
                @input="touched['option1'] = true"
                @blur="checkField('option1')"
            /><br />
            <Input
                label="Opção 2"
                v-model="vt.option2"
                placeholder="Digite a 2ª opção"
                isRequired="true"
                :error="errors['option2']"
                @input="touched['option2'] = true"
                @blur="checkField('option2')"
            /><br />
            <Input
                label="Opção 3"
                v-model="vt.option3"
                placeholder="Digite a 3ª opção"
                :error="errors['option3']"
                @input="touched['option3'] = true"
                @blur="checkField('option3')"
            /><br />
            <input class="create" type="submit" />{{ " " }}
            <button class="cancel" @click="$emit('cancel')">Cancelar</button>
        </form>
    </div>
</template>
<script>
import Input from "./Input.vue";
import { minLengthValidation, requiredValidation } from "./validations";

const validate = {
    statement: (value) => minLengthValidation(3, value),
    option1: requiredValidation,
    option2: requiredValidation,
};

export default {
    components: {
        Input,
    },
    props: ["vote"],
    data() {
        const { statement, options } = this.vote || {};
        const [option1, option2, option3] = options || [];
        return {
            vt: {
                statement: statement || "",
                option1: option1.option || "",
                option2: option2.option || "",
                option3: option3?.option || "",
            },
            errors: {},
            touched: {},
        };
    },
    methods: {
        checkField(name) {
            const value = this.vt[name];
            const error = validate[name] ? validate[name](value) : null;
            const nameError = this.touched[name] ? error : null;
            this.errors[name] = nameError;
        },
        onSubmit() {
            Object.keys(this.vt).forEach((field) => {
                this.touched[field] = true;
                this.checkField(field);
            });
            const errorsIsEmpty = !Object.values(this.errors).some((v) => v);
            if (errorsIsEmpty) {
                const options = [
                    {
                        option: this.vt.option1,
                        count: 0,
                    },
                    {
                        option: this.vt.option2,
                        count: 0,
                    },
                    {
                        option: this.vt.option3 || "",
                        count: 0,
                    },
                ].filter((o) => o && o.option.trim() !== "");
                this.$emit("update", {
                    statement: this.vt.statement,
                    options: options,
                });
            }
        },
    },
};
</script>
<style lang="scss">
</style>

// form-votacao-online/src/app/vote-form/vote-form.component.ts
import { Component, EventEmitter, Input, OnInit, Output, } from '@angular/core';

type OptionsType = {
    option: string,
    count: number
}

type VoteType = {
    statement: string,
    options: OptionsType[]
};

type DataVoteType = {
    statement: string,
    voteOption1: string,
    voteOption2: string,
    voteOption3: string,
}

@Component({
    selector: 'vote-form',
    templateUrl: './vote-form.component.html',
    styleUrls: ['./vote-form.component.scss']
})
export class VoteFormComponent implements OnInit {
    @Input() vote!: VoteType;
    @Output() cancel = new EventEmitter();
    @Output() update = new EventEmitter();
    vt: DataVoteType;

    constructor() {
        this.vt = {} as DataVoteType;
    }

    ngOnInit() {
        const { statement, options } = this.vote || {};
        const [option1, option2, option3] = options || [];
        this.vt = {
            statement: statement || '',
            voteOption1: option1.option || '',
            voteOption2: option2.option || '',
            voteOption3: option3?.option || '',
        };
    }

    onSubmit(e: Event) {
        var form = document.getElementsByClassName('needs-validation')[0] as HTMLFormElement;
        if (form.checkValidity() === false) {
            e.preventDefault();
            e.stopPropagation();
        } else {
            const options = [
                {
                    option: this.vt.voteOption1,
                    count: 0
                },
                {
                    option: this.vt.voteOption2,
                    count: 0
                },
                {
                    option: this.vt.voteOption3 || '',
                    count: 0
                }
            ].filter((o) => o && o.option.trim() !== '');
            this.update.emit({
                statement: this.vt.statement,
                options
            });
        }
        form.classList.add('was-validated');
    }

}

<form class="needs-validation">
    <div class="mb-3">
        <label for="statement" class="form-label">Enunciado*</label>
        <textarea [(ngModel)]="vt.statement" name="statement" type="textarea" class="form-control" id="statement"
            minlength="3" placeholder="Digite o enunciado..." required></textarea>
        <div class="invalid-feedback">O campo é obrigatório e deve conter pelo menos 3 caracteres!</div>
    </div>
    <div class="mb-3">
        <label for="option1" class="form-label">Opção 1*</label>
        <input [(ngModel)]="vt.voteOption1" name="option1" type="text" class="form-control" id="option1"
            placeholder="Digite a opção 1..." required>
    </div>
    <div class="mb-3">
        <label for="option2" class="form-label">Opção 2*</label>
        <input [(ngModel)]="vt.voteOption2" name="option2" type="text" class="form-control" id="option2"
            placeholder="Digite a opção 2..." required>
    </div>
    <div class="mb-3">
        <label for="option3" class="form-label">Opção 3</label>
        <input [(ngModel)]="vt.voteOption3" name="option3" type="text" class="form-control" id="option3"
            placeholder="Digite a opção 3...">
    </div>
    <div class="mb-3">
        <span class="text-muted">(*) campos obrigatórios</span><br>
    </div>
    <button type="submit" class="btn btn-primary" (click)="onSubmit($event)">Salvar</button>{{' '}}
    <a class="btn btn-secondary" (click)="cancel.emit()">Cancelar</a>
</form>
