// form-votacao-online/src/app/resultado/resultado.component.ts
import { Component, Input, OnInit } from '@angular/core';

type OptionsType = {
    count: number,
    option: string
}

@Component({
    selector: 'resultado',
    templateUrl: './resultado.component.html',
    styleUrls: ['./resultado.component.scss']
})
export class ResultadoComponent implements OnInit {
    @Input() voteOptions!: OptionsType[];

    ngOnInit() {
        console.log(this.voteOptions);
    }

    totalVotos = () => {
        console.log(this.voteOptions);
        let total = 0
        this.voteOptions.forEach(option => {
            total += option.count
        })
        return total
    }

    total = this.totalVotos();

}

<div>
    <p *ngFor="let option of voteOptions; index as i">
        {{i+1}}. {{option.option}} - {{option.count}} votos ({{(option.count/total)*100}}%)
    </p>
</div>

// form-votacao-online/src/components/Resultado/index.tsx
import React from "react";
import './style.scss'

type VoteOptionsType = {
    option: string;
    count: number;
}

type Props = {
    voteOptions: VoteOptionsType[];
}

const Resultado = ({ voteOptions }: Props) => {
    const totalVotos = () => {
        let total = 0
        voteOptions.forEach(option => {
            total += option.count
        })
        return total
    }

    const total = totalVotos();

    const resultado = voteOptions.map((option, index) => (
        <p key={index}>
            {index + 1}. {option.option} - {option.count} ({(option.count / total) * 100}%)
        </p>
    ))
    return (
        <div>
            {resultado}
        </div>
    )
}

export default Resultado;
