// form-votacao-online/src/components/CardVotacao/index.tsx
import React, { useState } from 'react'
import Cabine from '../Cabine'
import Resultado from '../Resultado'

import './style.scss'

type VoteOptionsType = {
    option: string;
    count: number;
}

type VoteType = {
    statement: string,
    voteOptions: VoteOptionsType[],
}

type Props = {
    vote: VoteType;
    onCancel: () => void;
}

const CardVotacao = ({ vote, onCancel }: Props) => {
    const pergunta = vote.statement;
    const opcoes = vote.voteOptions;

    const [mode, setMode] = useState('open');

    let panel;

    function votar(index: number) {
        opcoes[index].count += 1
        setMode('closed');
    }

    if (mode === 'open') {
        panel = (
            <div>
                <Cabine voteOptions={opcoes} onVote={votar} />
            </div >
        )
    } else {
        panel = (
            <Resultado voteOptions={opcoes} />
        )
    }

    return (
        <div className="containerCard">
            <div className="question">
                <h2>{pergunta}</h2>
            </div>
            {panel}
            <button className="button" onClick={() => onCancel()}>Voltar</button>
        </div >
    )
}

export default CardVotacao;

// form-votacao-online/src/app/card-votacao/card-votacao.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { VoteService } from '../vote-service.service';

type OptionsType = {
    option: string,
    count: number
}

@Component({
    selector: 'card-votacao',
    templateUrl: './card-votacao.component.html',
    styleUrls: ['./card-votacao.component.scss']
})
export class CardVotacaoComponent implements OnInit {
    @Input()
    statement!: string
    @Input()
    options!: OptionsType[]
    @Output() back = new EventEmitter();

    localOptions: OptionsType[] = [];
    mode: string = 'open';

    constructor(public voteService: VoteService) { }

    ngOnInit() {
        this.localOptions = this.options;
    }


    vote(index: number) {
        this.localOptions[index].count += 1;
    }

    showResult() {
        this.mode = 'closed';
    }

}

<div class="container">
    <div class="question">
        <h2>{{statement}}</h2>
    </div>
    <div *ngIf="mode === 'open'">
        <cabine [options]="localOptions" (click)="vote($event); showResult()">
        </cabine>
    </div>
    <div *ngIf="mode !== 'open'">
        <resultado *ngIf="localOptions" [voteOptions]="localOptions"></resultado>
    </div>
    <button class="button" (click)="back.emit()">Voltar</button>
</div>
