// form-votacao-online.old/src/app/form-vote/form-vote.component.ts
import { Component, Input, Output, OnInit, EventEmitter } from '@angular/core';
import { FormGroup } from '@angular/forms';


interface VoteType {
    statement: string;
    options: string[];
};

@Component({
    selector: 'form-vote',
    templateUrl: './form-vote.component.html',
    styleUrls: ['./form-vote.component.scss']
})
export class FormVoteComponent implements OnInit {
    @Input() vote!: VoteType;
    model = {
        statement: '',
        options: [],
    }
    @Output() update = new EventEmitter();
    @Output() cancel = new EventEmitter();
    votes: any;
    ngOnInit() {
        const { statement, options } = this.vote || {};
        const [option1, option2, option3] = options || []
        this.votes = {
            statement,
            option1,
            option2,
            option3
        };
    }

    onSubmit() {
        const options = [
            this.votes.option1,
            this.votes.option2,
            this.votes.option3].filter((o) => o && o.trim() !== '');
        this.update.emit({
            statement: this.votes.statement,
            options
        });

        console.log(this.votes);
    }
}
<form (ngSubmit)="onSubmit()">
    Enunciado da votação: <input class="" name="statement"><br>
    Opção 1: <input name="option1" placeholder="Opção 1" required><br>
    Opção 2: <input name="option2" placeholder="Opção 2" required><br>
    Opção 3: <input name="option3" placeholder="Opção 3"><br>
    <input class="btn btn-default" type="submit" value="Salvar">
</form>

// form-votacao-online/src/components/FormVote.svelte
<script>
    import { createEventDispatcher } from "svelte";
    import { schema } from "../schema";
    import {
        Button,
        Form,
        FormGroup,
        FormText,
        Input,
        Label,
    } from "sveltestrap";
    const dispatch = createEventDispatcher();

    export let vote;

    const { statement, options } = vote || {};
    const [option1, option2, option3] = options || [];

    let values = {
        statement: statement,
        option1: option1,
        option2: option2,
        option3: option3,
    };

    let errors = {};

    const extractErrors = (err) => {
        return err.inner.reduce((acc, err) => {
            return { ...acc, [err.path]: err.message };
        }, {});
    };

    const submitHandler = () => {
        schema
            .validate(values, { abortEarly: false })
            .then(() => {
                const fullOptions = [
                    values.option1,
                    values.option2,
                    values.option3,
                ];
                const filteredOptions = fullOptions.filter(
                    (option) => option && option.trim() !== ""
                );
                dispatch("update", {
                    statement: values.statement,
                    options: filteredOptions,
                });
                errors = {};
            })
            .catch((err) => (errors = extractErrors(err)));
    };
</script>

<div>
    <h2>Formulário</h2>
    <form on:submit|preventDefault={submitHandler}>
        <FormGroup>
            <Label for="statement">Enunciado da votação</Label>
            <Input
                type="textarea"
                name="statement"
                bind:value={values.statement}
                placeholder="Digite o enunciado..."
                invalid={errors.statement}
                feedback={errors.statement}
            />
        </FormGroup>
        <FormGroup>
            <Label for="option1">Opção 1</Label>
            <Input
                type="text"
                name="option1"
                bind:value={values.option1}
                placeholder="Opção 1..."
                invalid={errors.option1}
                feedback={errors.option1}
            />
        </FormGroup>
        <FormGroup>
            <Label for="option2">Opção 2</Label>
            <Input
                type="text"
                name="option2"
                bind:value={values.option2}
                placeholder="Opção 2..."
                invalid={errors.option2}
                feedback={errors.option2}
            />
        </FormGroup>
        <FormGroup>
            <Label for="option3">Opção 3</Label>
            <Input
                type="text"
                name="option3"
                bind:value={values.option3}
                placeholder="Opção 3..."
            />
        </FormGroup>
        <Button color="primary" type="submit">Enviar</Button>
        <Button color="secondary" on:click={(e) => dispatch("cancel")}
            >Cancelar
        </Button>
    </form>
</div>

<style lang="scss">
</style>
