// form-votacao-online/src/app/vote-list/vote-list.component.ts
import { Component } from '@angular/core';
import { VoteService } from '../vote-service.service';

type OptionsType = {
    option: string,
    count: number
}

type VoteType = {
    statement: string,
    options: OptionsType[]
};

@Component({
    selector: 'vote-list',
    templateUrl: './vote-list.component.html',
    styleUrls: ['./vote-list.component.scss']
})
export class VoteListComponent {
    mode: string = 'view';
    current: number = 0;

    constructor(public voteService: VoteService) { }

    addVote() {
        this.mode = 'add';
        this.voteService.createVote();
        this.current = this.voteService.votes.length - 1;
    }

    editVote(index: number) {
        this.current = index;
        this.mode = 'edit';
    }

    removeVote(index: number) {
        this.voteService.deleteVote(index);
    }

    updateChanges(vote: VoteType) {
        this.voteService.updateVote(vote, this.current);
        this.mode = 'view'
    }

    cancelChanges() {
        if (this.mode === 'add') {
            this.voteService.deleteVote(this.voteService.votes.length - 1)
        }
        this.mode = 'view'
    }

    showVote(index: number) {
        this.current = index;
        this.mode = 'show';
    }
}
<div *ngIf="mode === 'view'" class="row justifiy-conten">
    <div class="col-4">
        <h2>Votações</h2>
    </div>
    <div class="w-100 d-none d-md-block"></div>
    <div class="col-4">
        <button class="btn btn-primary" (click)="addVote()">Nova votação</button>
    </div>
    <div class="w-100 d-none d-md-block"></div>
    <div class="col-6">
        <p *ngFor="let vote of voteService.votes; index as i">
            <span><b>Enunciado da votação:</b> {{vote.statement}} - </span>
            <button class="btn btn-warning" (click)="editVote(i)">Editar</button>{{' '}}
            <button class="btn btn-danger" (click)="removeVote(i)">Remover</button>{{' '}}
            <button class="btn btn-success" (click)="showVote(i)">Usar</button>{{' '}}
        </p>
    </div>
</div>
<div *ngIf="mode === 'show'">
    <card-votacao [statement]="voteService.votes[current].statement" [options]="voteService.votes[current].options">
    </card-votacao>
</div>
<div *ngIf="mode !== 'view' && mode !== 'show'" class="row">
    <div class="col-2">
        <h2>Formulário</h2>
    </div>
    <div class="w-100 d-none d-md-block"></div>
    <div class="col-5">
        <vote-form [vote]="voteService.votes[current]" (update)="updateChanges($event)" (cancel)="cancelChanges()">
        </vote-form>
    </div>
</div>

// form-votacao-online/src/components/VoteList.svelte
<script>
    import FormVote from "./FormVote.svelte";
    import CardVotacao from "./CardVotacao.svelte";
    import { Button } from "sveltestrap";
    import { voteList, createVoteList } from "../votes";

    let mode = "view";
    let current = 0;
    let options = [];

    let vtList = createVoteList();

    function addVote() {
        vtList.create();
        current = $vtList.length - 1;
        mode = "add";
    }

    function editVote(index) {
        current = index;
        mode = "edit";
    }

    function removeVote(index) {
        vtList.remove(index);
    }

    function showVote(index) {
        current = index;
        $vtList[current].options.forEach((o) => {
            options.push({
                option: o,
                count: 0,
            });
        });
        mode = "show";
    }

    function updateChanges({ detail }) {
        vtList.change(detail, current);
        mode = "view";
    }

    function cancelChanges() {
        mode = "view";
    }
</script>

<div>
    {#if mode === "view"}
        <div class="containerList">
            <h2>Votações</h2>
            <Button color="primary" on:click={(e) => addVote()}
                >Criar votação</Button
            >

            {#each $vtList as vote, index}
                <p>
                    <b>Enunciado: </b>
                    {vote.statement}
                    <Button color="warning" on:click={(e) => editVote(index)}
                        >Edita</Button
                    >
                    <Button color="danger" on:click={(e) => removeVote(index)}
                        >Remove</Button
                    >
                    <Button color="success" on:click={(e) => showVote(index)}
                        >Mostrar</Button
                    >
                    <br />
                    <b>Opções: </b>
                    {#each vote.options as o, i}
                        <span>
                            {o}
                            {#if i < vote.options.length - 1}
                                <span>/ </span>
                            {/if}
                        </span>
                    {/each}
                </p>
            {/each}
        </div>
    {:else if mode === "show"}
        <CardVotacao statement={$vtList[current].statement} {options} />
    {:else}
        <div class="containerForm">
            <FormVote
                vote={$vtList[current]}
                on:cancel={cancelChanges}
                on:update={(e) => updateChanges(e)}
            />
        </div>
    {/if}
</div>

<style lang="scss">
    .containerList {
        width: 600px;
    }

    .containerForm {
        width: 300px;
    }
</style>
